# Generated by Django 3.1.7 on 2021-03-22 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, null=True)),
                ('celular', models.CharField(blank=True, help_text='Celular para contato', max_length=20, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('observacao', models.TextField(blank=True, max_length=150, null=True)),
                ('tipo_pessoa', models.CharField(choices=[('PF', 'Pessoa Fisica'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_update', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusVeiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='locadora.pessoa')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('cnpj', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('rg', models.CharField(max_length=20, unique=True)),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('data_abertura', models.DateField()),
                ('sexo', models.CharField(max_length=1)),
                ('estado_civil', models.CharField(max_length=1, verbose_name='Estado civil')),
            ],
            bases=('locadora.pessoa',),
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('renavam', models.CharField(max_length=15)),
                ('chassi', models.CharField(max_length=30)),
                ('cor', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('n_portas', models.IntegerField()),
                ('tipo_combustivel', models.CharField(max_length=100)),
                ('cambio', models.CharField(blank=True, max_length=50, null=True)),
                ('quilometragem', models.IntegerField()),
                ('nivel_tanque', models.FloatField(blank=True, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_locacao', models.FloatField(blank=True)),
                ('imagem_perfil', models.ImageField(blank=True, null=True, upload_to='locadora/media')),
                ('observacao', models.TextField(blank=True, max_length=150, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_update', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locadora.statusveiculo')),
                ('proprietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locadora.proprietario')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissao', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='locadora.permissao')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImagensVeiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='locadora/media')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locadora.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(blank=True, max_length=255)),
                ('bairro', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=15)),
                ('cidade', models.CharField(max_length=50)),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('cep', models.CharField(max_length=12, verbose_name='CEP')),
                ('pessoa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locadora.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='ArquivosDados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='locadora/dados')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_update', models.DateTimeField(auto_now=True)),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locadora.pessoa')),
            ],
        ),
    ]
