# Generated by Django 3.1.7 on 2021-03-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='observacao',
        ),
        migrations.AddField(
            model_name='proprietario',
            name='observacao',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Estado civil'),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='sexo',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
