# Generated by Django 3.1.7 on 2021-03-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0002_auto_20210323_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietario',
            name='data_abertura',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Abertura'),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='data_nascimento',
            field=models.DateField(null=True, verbose_name='Data de Nascimento'),
        ),
    ]
