# Generated by Django 3.1.7 on 2021-03-23 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locadora', '0004_auto_20210323_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietario',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='locadora.pessoa')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('sexo', models.CharField(blank=True, max_length=1, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=1, null=True, verbose_name='Estado civil')),
                ('numero_cnh', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Nº CNH')),
                ('validade_cnh', models.DateField(blank=True, unique=True, verbose_name='Validade CNH')),
                ('categoria_cnh', models.CharField(blank=True, max_length=5, null=True, verbose_name='Categoria CNH')),
                ('observacao', models.TextField(blank=True, max_length=150, null=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('locadora.pessoa',),
        ),
    ]
