# Generated by Django 3.1.7 on 2021-03-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0006_auto_20210323_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locacao',
            name='hora_locacao',
        ),
        migrations.AlterField(
            model_name='locacao',
            name='data_locacao',
            field=models.DateTimeField(),
        ),
    ]
