# Generated by Django 3.1.7 on 2021-03-24 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0007_auto_20210323_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='chassi',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='renavam',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
