# Generated by Django 3.1.7 on 2021-03-26 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0009_auto_20210324_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='locadora.pessoa')),
                ('cpf', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='CPF')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data Nascimento')),
                ('sexo', models.CharField(blank=True, max_length=1, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=1, null=True, verbose_name='Estado civil')),
                ('salario', models.FloatField(blank=True, null=True)),
                ('data_contratacao', models.DateField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, max_length=150, null=True)),
            ],
            bases=('locadora.pessoa',),
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cnpj',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='data_abertura',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='rg',
        ),
        migrations.RemoveField(
            model_name='locacao',
            name='categoria_cnh',
        ),
        migrations.RemoveField(
            model_name='locacao',
            name='numero_cnh',
        ),
        migrations.RemoveField(
            model_name='locacao',
            name='validade_cnh',
        ),
        migrations.RemoveField(
            model_name='locacao',
            name='valor_seguro',
        ),
        migrations.RemoveField(
            model_name='proprietario',
            name='cnpj',
        ),
        migrations.RemoveField(
            model_name='proprietario',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='proprietario',
            name='data_abertura',
        ),
        migrations.RemoveField(
            model_name='proprietario',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='proprietario',
            name='rg',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='CPF/CNPJ'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_nascimento_abertura',
            field=models.DateField(blank=True, null=True, verbose_name='Data Nascimento / Abertura'),
        ),
        migrations.AddField(
            model_name='proprietario',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='CPF/CNPJ'),
        ),
        migrations.AddField(
            model_name='proprietario',
            name='data_nascimento_abertura',
            field=models.DateField(blank=True, null=True, verbose_name='Data Nascimento / Abertura'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='data_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
