# Generated by Django 3.1.7 on 2021-03-26 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0010_auto_20210325_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivosdados',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='locadora/media'),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='locadora/media'),
        ),
    ]
