# Generated by Django 3.1.7 on 2021-03-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0011_auto_20210325_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='hora_devolucao',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='hora_inicio',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_devolucao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_inicio',
            field=models.DateTimeField(),
        ),
    ]
