# Generated by Django 3.1.7 on 2021-03-31 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0012_auto_20210329_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locacao',
            name='hora_devolucao',
        ),
        migrations.AddField(
            model_name='locacao',
            name='valor_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='data_devolucao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='data_locacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
