# Generated by Django 3.1.7 on 2021-03-31 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0013_auto_20210330_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='valor_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
