# Generated by Django 3.1.7 on 2021-04-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0014_auto_20210330_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacao',
            name='hora_devolucao',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locacao',
            name='hora_locacao',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='data_devolucao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='data_locacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
