# Generated by Django 3.1.7 on 2021-04-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0015_auto_20210401_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locacao',
            name='hora_devolucao',
        ),
        migrations.RemoveField(
            model_name='locacao',
            name='hora_locacao',
        ),
        migrations.AlterField(
            model_name='locacao',
            name='data_devolucao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='data_locacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
