# Generated by Django 3.1.7 on 2021-04-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0016_auto_20210401_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacao',
            name='hora_devolucao',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locacao',
            name='hora_locacao',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
