# Generated by Django 3.1.7 on 2021-04-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0018_auto_20210401_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacao',
            name='data_devolucao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='data_locacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
