# Generated by Django 3.1.7 on 2021-04-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0020_auto_20210402_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='hora_devolucao',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
