# Generated by Django 3.1.7 on 2021-04-05 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0021_auto_20210404_1407'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
        migrations.DeleteModel(
            name='Permissao',
        ),
    ]
